Fixed vi command

diff --git a/install/tmux-install b/install/tmux-install
--- a/install/tmux-install
+++ b/install/tmux-install
@@ -1,14 +1,23 @@
 #!/bin/bash
 
+# Script for installing tmux on systems where you don't have root access.
+# tmux will be installed in $HOME/local/bin.
+# It's assumed that wget and a C/C++ compiler are installed.
+
+# exit on error
+#set -e
+
+TMUX_VERSION=2.5
+
 sudo apt-get -y autoremove tmux
 sudo apt-get install -y exuberant-ctags cmake libevent-dev libncurses5-dev
+
 [ ! -d ~/tmp ]  &&  mkdir ~/tmp
 cd ~/tmp
-varTmux=tmux-2.4
-wget https://github.com/tmux/tmux/releases/download/2.4/$varTmux.tar.gz
-tar -xzvf $varTmux.tar.gz
-rm $varTmux.tar.gz
-cd $varTmux
+wget https://github.com/tmux/tmux/releases/download/$TMUX_VERSION/tmux-$TMUX_VERSION.tar.gz
+tar -xzvf tmux-$TMUX_VERSION.tar.gz
+rm tmux-$TMUX_VERSION.tar.gz
+cd tmux-$TMUX_VERSION
 ./configure    ||  { echo "Error executing ./config" ; exit ; }
 make           ||  { echo "Error executing make" ; exit ; }
 sudo make install
@@ -24,3 +33,49 @@ fi
 echo "========================================================================"
 echo "Tmux installed"
 echo "========================================================================"
+
+# create our directories
+# mkdir -p $HOME/local $HOME/tmux_tmp
+# cd $HOME/tmux_tmp
+
+# download source files for tmux, libevent, and ncurses
+# wget https://github.com/tmux/tmux/releases/download/$TMUX_VERSION/tmux-$TMUX_VERSION.tar.gz  ||  { echo "Error downloading tmux" ; exit ; }
+# wget https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz  ||  { echo "Error downloading libevent" ; exit ; }
+# wget ftp://ftp.invisible-island.net/ncurses/ncurses.tar.gz  ||  { echo "Error downloading ncurses" ; exit ; }
+
+# extract files, configure, and compile
+
+############
+# libevent #
+############
+# tar xvzf libevent-2.1.8-stable.tar.gz
+# cd libevent-2.1.8-stable
+# ./configure --prefix=$HOME/local --disable-shared
+# make
+# make install
+# cd ..
+
+############
+# ncurses  #
+############
+# tar xvzf ncurses.tar.gz
+# cd ncurses
+# ./configure --prefix=$HOME/local
+# make
+# make install
+# cd ..
+
+############
+# tmux     #
+############
+# tar xvzf tmux-${TMUX_VERSION}.tar.gz
+# cd tmux-${TMUX_VERSION}
+# ./configure CFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-L$HOME/local/lib -L$HOME/local/include/ncurses -L$HOME/local/include"
+# CPPFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-static -L$HOME/local/include -L$HOME/local/include/ncurses -L$HOME/local/lib" make
+# cp tmux $HOME/local/bin
+# cd ..
+
+# cleanup
+# rm -rf $HOME/tmux_tmp
+#
+# echo "$HOME/local/bin/tmux is now available. You can optionally add $HOME/local/bin to your PATH."
